name: Node CI

on:
  push:
    paths:
      - "js/**"
      - ".github/workflows/node.yml"
  pull_request:
    paths:
      - "js/**"
      - ".github/workflows/node.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: js/package-lock.json
      - run: npm ci
      - run: npm test
